### ISSUE TITLE
GPT2 tokenizer in llm pipeline

### ISSUE THREAD

**Issue by nsankar** [JohnNay/llm-lobbyist#1]
@JohnNay It was great to read your awesome research paper.
Why did you choose to use GPT-2 for the tokenizer  in the example code ? Vs other tokeneizers available in HuggingFace for instance ? . 

i.e. self.tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

**Comment by JohnNay** [comment]
@nsankar thanks! Do you know of a better tokenizer function to use in place of that? would love to swap that out if so.

**Comment by nsankar** [comment]
@JohnNay Not sure of it now. I will try out a few options (mainly from hugging face and google) and revert.
